//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace longhu.his.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class drug_deliveries
    {
        public int Id { get; set; }
        public int delivery_user_id { get; set; }
        public int drug_id { get; set; }
        public int Deliveryi_type { get; set; }
        public int Dg_Destroy_auditor_id { get; set; }
        public System.DateTime Dg_destory_audit_date { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
        public string Updatedby { get; set; }
        public Nullable<int> Delete_flag { get; set; }
    }
}
