//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace longhu.his.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBConnection : DbContext
    {
        public DBConnection()
            : base("name=DBConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<drug_categories> drug_categories { get; set; }
        public virtual DbSet<drug_deliveries> drug_deliveries { get; set; }
        public virtual DbSet<drug_deliveries_details> drug_deliveries_details { get; set; }
        public virtual DbSet<drug_entryType> drug_entryType { get; set; }
        public virtual DbSet<drug_shelves> drug_shelves { get; set; }
        public virtual DbSet<drug_shelves_maping> drug_shelves_maping { get; set; }
        public virtual DbSet<drug_specification> drug_specification { get; set; }
        public virtual DbSet<drug_supplier> drug_supplier { get; set; }
        public virtual DbSet<drug_units> drug_units { get; set; }
        public virtual DbSet<drug> drugs { get; set; }
        public virtual DbSet<sys_permission> sys_permission { get; set; }
        public virtual DbSet<sys_roles> sys_roles { get; set; }
        public virtual DbSet<sys_users> sys_users { get; set; }
        public virtual DbSet<sys_usr_type> sys_usr_type { get; set; }
        public virtual DbSet<sys_permission_roles> sys_permission_roles { get; set; }
        public virtual DbSet<sys_user_roles> sys_user_roles { get; set; }
        public virtual DbSet<View_GetUserInfo> View_GetUserInfo { get; set; }
        public virtual DbSet<View_Permission_Roles> View_Permission_Roles { get; set; }
        public virtual DbSet<godown_entry> godown_entry { get; set; }
        public virtual DbSet<godown_entry_details> godown_entry_details { get; set; }
        public virtual DbSet<View_GetNotNotedDrugEntries> View_GetNotNotedDrugEntries { get; set; }
    }
}
