//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace longhu.his.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_roles
    {
        public int Id { get; set; }
        public string Rolename { get; set; }
        public string Rolename_ab { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Createdby { get; set; }
        public Nullable<int> Delete_flag { get; set; }
    }
}
