//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace longhu.his.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_users
    {
        public int Id { get; set; }
        public int userTypeId { get; set; }
        public int departmentId { get; set; }
        public string Account { get; set; }
        public string password { get; set; }
        public string userName { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Adress { get; set; }
        public string Address1 { get; set; }
        public string Mobile { get; set; }
        public string Telphone { get; set; }
        public string QQ { get; set; }
        public string Email { get; set; }
        public string residentID { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Createdby { get; set; }
        public Nullable<int> Delete_flag { get; set; }
    
        public virtual sys_usr_type sys_usr_type { get; set; }
    }
}
