//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace longhu.his.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Permission_Roles
    {
        public int roleId { get; set; }
        public int permisionId { get; set; }
        public string Rolename { get; set; }
        public string Rolename_ab { get; set; }
        public string Permissionname { get; set; }
        public string Permissionname_ab { get; set; }
        public string permissions { get; set; }
    }
}
