//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace longhu.his.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetNotNotedDrugEntries
    {
        public int Id { get; set; }
        public int Entry_user_id { get; set; }
        public string purchase_note_id { get; set; }
        public int drug_entryType_id { get; set; }
        public string entryName { get; set; }
        public string entryName_ab { get; set; }
        public int purchase_auditor_id { get; set; }
        public string purchase_auditor_Name { get; set; }
        public string purchase_auditor_Account { get; set; }
        public string purchase_auditor_Mobile { get; set; }
        public string purchase_auditor_Telphone { get; set; }
        public string purchase_auditor_Adress { get; set; }
        public string purchase_Name { get; set; }
        public string purchase_Account { get; set; }
        public string purchase_Mobile { get; set; }
        public string purchase_Telphone { get; set; }
        public string purchase_Adress { get; set; }
        public string billNumer { get; set; }
        public Nullable<System.DateTime> bill_date { get; set; }
        public int supplier_id { get; set; }
        public string supplier_name { get; set; }
        public string supplier_name_ab { get; set; }
        public string supplier_Contacts { get; set; }
        public string supplier_Telephone { get; set; }
        public string supplier_Mobile { get; set; }
        public string supplier_Address { get; set; }
        public int dg_Category_id { get; set; }
        public string Category_name { get; set; }
        public string Category_name_ab { get; set; }
        public Nullable<int> parentId { get; set; }
        public int dg_specification_id { get; set; }
        public string Specification_name { get; set; }
        public string Specific_name_ab { get; set; }
        public int dg_units_id { get; set; }
        public string Units_name { get; set; }
        public string Units_name_ab { get; set; }
        public string dg_name { get; set; }
        public string dg_name_ab { get; set; }
        public string Description { get; set; }
        public string dg_brand { get; set; }
        public string dg_plant { get; set; }
        public decimal dg_price { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
        public string Updatedby { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Delete_flag { get; set; }
    }
}
